--- #YAML:1.0
name:               Sledge-Template-Xslate
version:            0.0.2
abstract:           Text::Xslate template system for Sledge
author:
    - Kenta Sato <kenta.sato.1990@gmail.com>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    File::Basename:       0
    File::Spec::Memoized:  0
    parent:               0
    Sledge:               0
    Sledge::TestPages:    0
    Test::More:           0
    Text::Xslate:         0
    version:              0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
